### ISSUE TITLE
screenshots plz

### ISSUE THREAD

**Issue by bubnenkoff** [ZILtoid1991/pixelperfectengine#1]
sbj

**Comment by ZILtoid1991** [comment]
![kepernyofelvetel 21](https://cloud.githubusercontent.com/assets/10679119/17272928/12dc4d04-56a4-11e6-8d8c-5c6191a478d3.png)
From version 0.9.0

Background is done by tiles, indirect rendering of the images.

**Comment by ZILtoid1991** [comment]
![kepernyofelvetel 659](https://cloud.githubusercontent.com/assets/10679119/17272941/7ec96f6a-56a4-11e6-959a-b2dbf201f5bf.png)
Latest screenshot from the experimental 0.9.1 version. Still unfinished, however it now has:

- direct rendering to SDL textures, enabling non-paletted images and transparencies
- a pretty GUI for the editor

I think I'll migrate my project to Visual Studio and make an experimental branch, where I publish the unfinished and unstable builds. Currently the tile-renderer is untested since I removed the possibility of rendering to 16 bit paletted bitmaps to remove some overhead and enable 32 bit stuff, and use 4 pixel simultaneous alpha-blending via SSE. First proper game for the engine probably going to be a Berzerk clone.

**Comment by ZILtoid1991** [comment]
Now there's even a video:
https://twitter.com/EvilReptoid/status/809461349268885505

**Comment by MggMuggins** [comment]
Could we see some example code using the engine as well?

**Comment by ZILtoid1991** [comment]
The closest is in PixelPerfectEditor. There's the editor itself and the program I used to test the TileLayer and the collision detection. If you can reverse engineer the code, you can learn from it.

Documentation in the future will include a basic tutorial. In the meanwhile refer to the available documentation in the source code.
