### ISSUE TITLE
Raspberry Pi 

### ISSUE THREAD

**Issue by aberba** [ZILtoid1991/pixelperfectengine#6]
What will take to target raspberry Pi

**Comment by MggMuggins** [comment]
Hmm. Well, I have very little knowledge of the way the program actually works, but so long as you have the sdl libs installed, as well as dub and the gdc (dmd doesn't have an arch release), it shouldn't take much. Note that I haven't actually gotten this thing running under Ubuntu yet, so I really don't know what it all entails. In any case, I'm willing to help out a bit. Let me know if you have any questions.

P.S. Are you a windows user learning to use a RPi, or a Linux user interested in doing a project with an RPi?

**Comment by aberba** [comment]
Linux

**Comment by ZILtoid1991** [comment]
Well, the engine currently depends on the SSE2 instruction set for alpha-blending, blitter, etc, and these functions are written in x86 assembly as these are just small code snippets. However it wouldn't be hard to rewrite these functions for either NEON (Pi2 and 3), for the VPU of the VideoCore4 processor (all Pi versions), or for either OpenGL ES or OpenVG. Here are the abstracts of the platform dependent functions in the Layer class:

- void colorLookup(ushort* src, void* dest, ubyte* palette, int length)

ushort is pointing to the Bitmap16Bit's data with offset, void points to a work buffer that is only allocated once per bitmap then it's being overwritten for each line, the length is in pixels. Work buffer's length is pixels times 4. Currently it works something like this in pseudocode:
`
int i = 0
while (i < length)
    *cast(*ubyte[4]) = *cast(*ubyte[4])(palette + *src)
    i++
    src++
`

- void createAlphaMask(void* src, void* alpha, int length)

Creates an AAAA mask out from the src's BGRA. Basically it just assigns the alpha 4 times to a doubleword, currently it's done by bitshifts and adding on register level, later I'll replace it with multiplying the alpha value by 0x1111. As long as it's efficient and works, it doesn't matter how it's done. Alpha has the same length as src.

-  void alphaBlend(void* src, void* dest, void* alpha, int length)

Blends src into dest on a pixel basis defined by alpha. Uses an integer based alpha. Formula per pixel is:

`
dest = (dest * (256 - alpha) + src * (1 + alpha)) >> 8
`

Please note that this function needs the data to be unpacked into 16 bit unsigned integers, then repacked into 8 bit ones, most vector processors support this kind of operations.

- void blitter(void* src, void* dest, void* alpha, int length)

Similar to the previous one but with blitter function. Intended for slower processors, however in most cases the performance gain is minimal due to memory bandwidth limitations. Its formula:

`
alpha2 = alpha == 0 ? 0xFFFFFFFF : 0
dest = (dest & alpha2) | src
`

Please note that alpha2 is generated on the fly in the register, most vector processors have packed compare instructions in them, the VPU of the VideoCore4 has its own specialized one called vbitplanes.

- void copyRegion(void* src, void* dest, int length)

Copies a region using the vector processor. Saves a lot of CPU time by not reading the alpha (or not even needing one to be generated) and by only writing to dest by sacrificing transparency. Useful for the lowermost layer, certain tile based graphics that only use the 0xFFFF tile for transparency, or for windowing.

- void flipHorizontal(void* src, int length)

Reverses the order of pixels horizontally using the vector processor while retaining the BGRA color order. 32bit bitmaps need a backbuffer to avoid corrupting the bitmap itself.

Final note: Most functions can be recreated on scalar processors, however alpha-blending will require heavy branching to lift some of the stress from the processor. That's when blitter might actually work the best. Currently I have limited resources and I want to get the editor up and running first (as well as solve the noise issues of my PC), but after my master's thesis I'm going to buy various cheap single board PCs for optimization. There might also be problems from the endianness, in which case the loader also needs to be modified.

Final note on BitmapDrawer: It also uses SSE2 for blitter (except for single pixel ones, then it uses the cmov instruction), except that it generates the mask on the fly with packed compare instructions (color index No.0 is always transparent to the BitmapDrawer.

**Comment by ZILtoid1991** [comment]
Version v0.9.2-rc1 might be able to build and run on a Pi, but it doesn't use either ARM NEON or any GPGPU acceleration, so it would be extremely slow.

As I don't plan to include a Raspberry Pi implementation into my master's thesis, I would happily let anybody to make an implementation of it for single-board computers in a separate branch, however I think it should be contained within its own file as a "video driver", especially as there are multiple GPUs among ARM devices (Broadcom Videocore, ARM Mali, nVidia Tegra, etc.).

**Comment by p0nce** [comment]
If you use regular `intel-intrinsics` you should get some acceleration on Raspberry Pi

**Comment by ZILtoid1991** [comment]
That will also help with most if not all single board computers. While the VideoCore GPU could be used for this purpose via programming tricks or now even OpenCL, many others (mostly older ARM Mali GPUs) cannot, and even then it's questionable due to drivers.

**Comment by ZILtoid1991** [comment]
Any further discussion of this topic will be done in the discussions tab.
